### ISSUE TITLE
App loses focus after `hideElement` called

### ISSUE THREAD

**Issue by rafal-kowalski** [Monar/react-aurora#3]
After modal is closed programmatically using `hideElement` method, browser focus stays on the element which is already deleted, so the new focus defaults to `<body>`. This prevents any `keypresseddown` event in our app until user clicks something on a page and focuses back to React

**Comment by Monar** [comment]
Hmmm I don't think what you are writing about is a part of the problem aurora is supposed to solve. To figure out what was the problem I've created a small playground: https://react-lioi9n.stackblitz.io (editor: https://stackblitz.com/edit/react-lioi9n). 

As you see focus flow is the same for "aurora modal" as for the "local modal", and I'd like to keep it this way rather then introduce some specific focus flow. Generally messing with focus is something I would rather not do with aurora there is too many corner cases to handle while aiming for general purpose library. Whats more the aurora api allows to do everything you implemented in #4 proposal only directly in your app using onClose and reacting to new element being added. 

About #4 I see few problems:
1. Handling focus as a core part of the library (described above why I'd rather not implement it)
2. Providing very specific implementation without option to disable, override modify behavior of it 
3. Not handling situation when element is no longer accessible during `returnFocus` 

From what I understand you should attack your problem by doing:
1. Use `document.addEventListener` for global listener of key events 
2. You need some custom js to handle keyboard events in your app to  select some element (eventually html tag autofocus on input), And I'd solve this problem the same way you would solve this for this "local modal", because you will louse focus in your app whenevery you remove any element having focus.
3. You can always listen to when `body` is focused as a sign that your app lost focus, :D and react to that by focusing one of app elements.

**Comment by rafal-kowalski** [comment]
Thank you for such detailed answer :smile: 
I understand why you do not want to introduce such behavior into library core and after all it turned out that its possible to fix our issue with API that is already provided with Aurora. (We've added additional reducer which manages focusing to previous element when `HIDE_ELEMENT` is called)
Thanks for you help!
